name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # main ブランチに push されたら実行
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Hugo をセットアップ
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Hugo でサイトをビルド
        run: hugo --minify

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo の出力フォルダ
          publish_branch: gh-pages

